"""
model_milp.py

MILP implementation for the Facility Location and Mill Pricing Problem (FLMPr).

This version implements MILP-3 from the paper:
"Facility location and pricing problem: discretized mill price and exact algorithms"

It assumes data is generated by data.py and passed as an FLMPrData object.
"""

from typing import Dict, Tuple, Any, List
import time

import gurobipy as gp
from gurobipy import GRB

from data import FLMPrData


SolutionDict = Dict[str, Any]


def solve_milp3(
    data: FLMPrData,
    time_limit: float | None = None,
    mip_gap: float | None = None,
    verbose: bool = True,
) -> SolutionDict:
    """
    Solve the MILP-3 formulation of FLMPr.

    Decision variables
    ------------------
    w[j] = 1 if facility j is opened, 0 otherwise.
    x[j,k] = 1 if facility j is opened with price level k, 0 otherwise.
    y[i,j,k] = 1 if customer i chooses facility j with price level k, 0 otherwise.

    Objective
    ---------
    Maximize total profit:
        revenue from served customers - fixed cost of opened facilities

    Main constraints
    ----------------
    1. Each open facility chooses exactly one price level:
        sum_k x[j,k] = w[j]

    2. Each customer chooses at most one facility-price option:
        sum_j,k y[i,j,k] <= 1

    3. A customer can choose an option only if that option is open:
        y[i,j,k] <= x[j,k]

    4. A customer cannot choose an option if total cost exceeds budget:
        y[i,j,k] = 0 if theta[i,j,k] > b[i]

    5. Closest assignment constraints, MILP-3:
        if option (j,k) is open, customer i cannot choose a more expensive option.
    """

    model = gp.Model("FLMPr_MILP3")
    model.Params.OutputFlag = 1 if verbose else 0

    if time_limit is not None:
        model.Params.TimeLimit = time_limit

    if mip_gap is not None:
        model.Params.MIPGap = mip_gap

    I = data.customers
    J = data.facilities
    K = data.price_levels

    # All facility-price options: Gamma = {(j,k): j in J, k in K_j}
    options: List[Tuple[int, int]] = [(j, k) for j in J for k in K[j]]

    # -------------------------
    # Decision variables
    # -------------------------
    w = model.addVars(J, vtype=GRB.BINARY, name="w")
    x = model.addVars(options, vtype=GRB.BINARY, name="x")
    y = model.addVars(
        [(i, j, k) for i in I for (j, k) in options],
        vtype=GRB.BINARY,
        name="y",
    )

    # -------------------------
    # Objective function
    # -------------------------
    revenue = gp.quicksum(
        data.demand[i] * data.price[j, k] * y[i, j, k]
        for i in I
        for (j, k) in options
    )

    opening_cost = gp.quicksum(
        data.fixed_cost[j] * w[j]
        for j in J
    )

    model.setObjective(revenue - opening_cost, GRB.MAXIMIZE)

    # -------------------------
    # Constraint 1:
    # If facility j is open, exactly one price level is selected.
    # If facility j is closed, no price level is selected.
    # -------------------------
    for j in J:
        model.addConstr(
            gp.quicksum(x[j, k] for k in K[j]) == w[j],
            name=f"one_price_if_open[{j}]",
        )

    # -------------------------
    # Constraint 2:
    # Each customer chooses at most one option.
    # A customer may also choose no option if every option is too expensive.
    # -------------------------
    for i in I:
        model.addConstr(
            gp.quicksum(y[i, j, k] for (j, k) in options) <= 1,
            name=f"at_most_one_option[{i}]",
        )

    # -------------------------
    # Constraint 3:
    # Customer i can choose facility-price option (j,k)
    # only if that option is selected by the company.
    # -------------------------
    for i in I:
        for (j, k) in options:
            model.addConstr(
                y[i, j, k] <= x[j, k],
                name=f"choose_only_if_open[{i},{j},{k}]",
            )

    # -------------------------
    # Constraint 4:
    # If theta_ijk > budget_i, customer i cannot choose option (j,k).
    # -------------------------
    for i in I:
        for (j, k) in options:
            if data.theta[i, j, k] > data.budget[i]:
                model.addConstr(
                    y[i, j, k] == 0,
                    name=f"budget_cut[{i},{j},{k}]",
                )

    # -------------------------
    # Constraint 5: MILP-3 closest assignment constraint.
    #
    # For each customer i and option (j,k):
    # If x[j,k] = 1, then all options with higher total cost than theta[i,j,k]
    # cannot be chosen by customer i.
    #
    # sum_{(m,n): theta_imn > theta_ijk} y[i,m,n] <= 1 - x[j,k]
    # -------------------------
    for i in I:
        for (j, k) in options:
            more_expensive_options = [
                (m, n)
                for (m, n) in options
                if data.theta[i, m, n] > data.theta[i, j, k]
            ]

            if more_expensive_options:
                model.addConstr(
                    gp.quicksum(y[i, m, n] for (m, n) in more_expensive_options)
                    <= 1 - x[j, k],
                    name=f"closest_assignment[{i},{j},{k}]",
                )

    # -------------------------
    # Optimize
    # -------------------------
    start_time = time.time()
    model.optimize()
    runtime = time.time() - start_time

    return _extract_solution(data, model, w, x, y, runtime)


def _extract_solution(
    data: FLMPrData,
    model: gp.Model,
    w,
    x,
    y,
    runtime: float,
) -> SolutionDict:
    """Extract a readable solution from the optimized Gurobi model."""

    result: SolutionDict = {
        "status": model.Status,
        "runtime": runtime,
        "objective": None,
        "mip_gap": None,
        "opened_facilities": [],
        "selected_prices": {},
        "assignments": {},
        "served_demand": 0.0,
        "total_revenue": 0.0,
        "total_opening_cost": 0.0,
    }

    if model.SolCount == 0:
        return result

    result["objective"] = model.ObjVal

    try:
        result["mip_gap"] = model.MIPGap
    except gp.GurobiError:
        result["mip_gap"] = None

    for j in data.facilities:
        if w[j].X > 0.5:
            result["opened_facilities"].append(j)
            result["total_opening_cost"] += data.fixed_cost[j]

    for j in data.facilities:
        for k in data.price_levels[j]:
            if x[j, k].X > 0.5:
                result["selected_prices"][j] = {
                    "price_level": k,
                    "price": data.price[j, k],
                }

    for i in data.customers:
        for j in data.facilities:
            for k in data.price_levels[j]:
                if y[i, j, k].X > 0.5:
                    revenue = data.demand[i] * data.price[j, k]
                    result["assignments"][i] = {
                        "facility": j,
                        "price_level": k,
                        "price": data.price[j, k],
                        "access_cost": data.access_cost[i, j],
                        "theta": data.theta[i, j, k],
                        "budget": data.budget[i],
                        "demand": data.demand[i],
                        "revenue": revenue,
                    }
                    result["served_demand"] += data.demand[i]
                    result["total_revenue"] += revenue

    return result


def print_solution(result: SolutionDict) -> None:
    """Print a readable solution summary."""

    print("\n========== SOLUTION SUMMARY ==========")
    print(f"Status: {result['status']}")
    print(f"Objective: {result['objective']}")
    print(f"Runtime: {result['runtime']:.4f} seconds")
    print(f"MIP gap: {result['mip_gap']}")

    print("\nOpened facilities:")
    print(result["opened_facilities"])

    print("\nSelected prices:")
    if not result["selected_prices"]:
        print("  No facility opened.")
    else:
        for j, info in result["selected_prices"].items():
            print(
                f"  Facility {j}: level {info['price_level']} "
                f"with price {info['price']:.2f}"
            )

    print("\nAssignments:")
    if not result["assignments"]:
        print("  No customers served.")
    else:
        for i, info in result["assignments"].items():
            print(
                f"  Customer {i} -> Facility {info['facility']} "
                f"(level {info['price_level']}, price={info['price']:.2f}, "
                f"access={info['access_cost']:.2f}, theta={info['theta']:.2f}, "
                f"budget={info['budget']:.2f}, demand={info['demand']:.2f})"
            )

    print("\nFinancial summary:")
    print(f"  Total revenue: {result['total_revenue']:.2f}")
    print(f"  Total opening cost: {result['total_opening_cost']:.2f}")
    print(f"  Served demand: {result['served_demand']:.2f}")
