# plot_scalability.py

import pandas as pd
import matplotlib.pyplot as plt


INPUT_FILE = "fair_summary_results.csv"


def plot_runtime(summary):
    data = summary.groupby(
        ["model", "n_customers"],
        as_index=False
    )["avg_runtime"].mean()

    plt.figure()

    for model in data["model"].unique():
        model_data = data[data["model"] == model]
        plt.plot(
            model_data["n_customers"],
            model_data["avg_runtime"],
            marker="o",
            label=model,
        )

    plt.xlabel("Number of customers")
    plt.ylabel("Average runtime (seconds)")
    plt.title("Average runtime by problem size")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("runtime_by_customers.png", dpi=300)
    plt.show()


def plot_constraints(summary):
    data = summary.groupby(
        ["model", "n_customers"],
        as_index=False
    )["avg_effective_constraints"].mean()

    plt.figure()

    for model in data["model"].unique():
        model_data = data[data["model"] == model]
        plt.plot(
            model_data["n_customers"],
            model_data["avg_effective_constraints"],
            marker="o",
            label=model,
        )

    plt.xlabel("Number of customers")
    plt.ylabel("Average effective constraints")
    plt.title("Average effective constraints by problem size")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("constraints_by_customers.png", dpi=300)
    plt.show()


def plot_lazy_cuts(summary):
    bbc_models = ["BBC", "BBC-Paper"]

    data = summary[summary["model"].isin(bbc_models)].groupby(
        ["model", "n_customers"],
        as_index=False
    )["avg_lazy_cuts"].mean()

    plt.figure()

    for model in data["model"].unique():
        model_data = data[data["model"] == model]
        plt.plot(
            model_data["n_customers"],
            model_data["avg_lazy_cuts"],
            marker="o",
            label=model,
        )

    plt.xlabel("Number of customers")
    plt.ylabel("Average lazy cuts")
    plt.title("Average lazy cuts generated by BBC variants")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("lazy_cuts_by_customers.png", dpi=300)
    plt.show()


def plot_objective(summary):
    data = summary.groupby(
        ["model", "n_customers"],
        as_index=False
    )["avg_objective"].mean()

    plt.figure()

    for model in data["model"].unique():
        model_data = data[data["model"] == model]
        plt.plot(
            model_data["n_customers"],
            model_data["avg_objective"],
            marker="o",
            label=model,
        )

    plt.xlabel("Number of customers")
    plt.ylabel("Average objective value")
    plt.title("Average objective by problem size")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("objective_by_customers.png", dpi=300)
    plt.show()


def main():
    summary = pd.read_csv(INPUT_FILE)

    plot_runtime(summary)
    plot_constraints(summary)
    plot_lazy_cuts(summary)
    plot_objective(summary)

    print("Plots saved:")
    print("- runtime_by_customers.png")
    print("- constraints_by_customers.png")
    print("- lazy_cuts_by_customers.png")
    print("- objective_by_customers.png")


if __name__ == "__main__":
    main()